name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: |
          pip install -e .[dev]
      - name: Lint (ruff)
        run: ruff check empathetic
      - name: Type Check (mypy)
        run: mypy empathetic
      - name: Tests
        run: coverage run -m pytest -q
      - name: Coverage Report
        run: coverage report